name: my-front
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIATJYTZ6ZTTXCJQKP7
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'index.html'
        env:
          AWS_S3_BUCKET: myspartas3

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: EFMH76LOZOOHN
          PATHS: '/index.html'
        continue-on-error: true